-- ECS Post Admin — Supabase schema for the ESP32 workstation flow.
--
-- This matches exactly what ECS_PostAdmin_v6.ino writes via the Supabase REST
-- API (PostgREST) and what dashboard.html reads back. Run this in the Supabase
-- SQL Editor for the project referenced by config.h / config.js.
--
-- Tables:
--   staff      - upserted on staff_id   (Prefer: resolution=merge-duplicates)
--   terminals  - upserted on terminal_id (Prefer: resolution=merge-duplicates)
--   logs       - one row inserted per completed workstation transaction

create table if not exists staff (
  staff_id   text primary key,
  name       text,
  role       text,
  station    text,
  rfid_uid   text,
  updated_at timestamptz not null default now()
);

create table if not exists terminals (
  terminal_id text primary key,
  model       text,
  brand       text,
  status      text,            -- in_queue | processing | released
  updated_at  timestamptz not null default now()
);

create table if not exists logs (
  id          bigint generated by default as identity primary key,
  terminal_id text,
  staff_id    text,
  station     text,            -- Receiving | Processing | Release
  task        text,            -- receive | process | release
  "timestamp" timestamptz,     -- firmware sends ended_at (ISO 8601)
  photo_url   text,
  ai_result   jsonb,           -- staff_name, staff_role, remarks, duration_sec,
                               -- items_checked, items_total, checklist, ...
  created_at  timestamptz not null default now()
);

create index if not exists idx_logs_timestamp on logs ("timestamp" desc);
create index if not exists idx_logs_created_at on logs (created_at desc);
create index if not exists idx_logs_terminal on logs (terminal_id);

-- Prototype access policies: the ESP32 uses the anon key to insert/upsert and
-- the dashboard uses the anon key to read. Tighten these before production.
alter table staff     enable row level security;
alter table terminals enable row level security;
alter table logs      enable row level security;

drop policy if exists anon_all_staff on staff;
drop policy if exists anon_all_terminals on terminals;
drop policy if exists anon_all_logs on logs;

create policy anon_all_staff     on staff     for all to anon using (true) with check (true);
create policy anon_all_terminals on terminals for all to anon using (true) with check (true);
create policy anon_all_logs      on logs      for all to anon using (true) with check (true);
