-- Supabase/Postgres schema for the TMS traceability backend.
-- Run this in Supabase SQL Editor before starting the backend, or allow the backend
-- to create these tables when SUPABASE_DB_URL is configured with schema privileges.

CREATE TABLE IF NOT EXISTS employees (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    role TEXT NOT NULL DEFAULT 'staff',
    username TEXT UNIQUE,
    password_hash TEXT,
    rfid_uid TEXT UNIQUE,
    active BOOLEAN NOT NULL DEFAULT true,
    created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS terminals (
    serial_number TEXT PRIMARY KEY,
    terminal_model TEXT NOT NULL,
    brand TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'In Queue',
    current_station TEXT,
    last_handled_by TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS receive_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    serial_number TEXT NOT NULL REFERENCES terminals(serial_number)
        ON UPDATE CASCADE ON DELETE CASCADE,
    terminal_model TEXT NOT NULL,
    brand TEXT NOT NULL,
    received_by TEXT NOT NULL,
    source TEXT,
    station_id TEXT,
    status TEXT NOT NULL,
    received_at TEXT NOT NULL,
    created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS release_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    serial_number TEXT NOT NULL REFERENCES terminals(serial_number)
        ON UPDATE CASCADE ON DELETE CASCADE,
    terminal_model TEXT NOT NULL,
    brand TEXT NOT NULL,
    released_by TEXT NOT NULL,
    destination TEXT,
    status TEXT NOT NULL,
    released_at TEXT NOT NULL,
    created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS assignments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    serial_number TEXT NOT NULL REFERENCES terminals(serial_number)
        ON UPDATE CASCADE ON DELETE CASCADE,
    terminal_model TEXT NOT NULL,
    brand TEXT NOT NULL,
    assigned_staff TEXT NOT NULL,
    task_name TEXT NOT NULL,
    started_at TEXT,
    ended_at TEXT,
    flagged_conditions TEXT,
    status TEXT NOT NULL,
    created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS inspection_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    serial_number TEXT NOT NULL REFERENCES terminals(serial_number)
        ON UPDATE CASCADE ON DELETE CASCADE,
    terminal_model TEXT NOT NULL,
    brand TEXT NOT NULL,
    inspection_task TEXT NOT NULL,
    inspected_by TEXT NOT NULL,
    remarks TEXT NOT NULL,
    inspected_at TEXT NOT NULL,
    evidence_path TEXT,
    created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS visual_analyses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    serial_number TEXT,
    station_id TEXT,
    source TEXT NOT NULL,
    image_path TEXT,
    model TEXT NOT NULL,
    prompt TEXT NOT NULL,
    result_text TEXT NOT NULL,
    result_json TEXT,
    recommended_status TEXT,
    created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type TEXT NOT NULL,
    message TEXT NOT NULL,
    actor TEXT,
    serial_number TEXT,
    station_id TEXT,
    created_at TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_receive_logs_received_at ON receive_logs(received_at DESC);
CREATE INDEX IF NOT EXISTS idx_release_logs_released_at ON release_logs(released_at DESC);
CREATE INDEX IF NOT EXISTS idx_events_created_at ON events(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_visual_analyses_created_at ON visual_analyses(created_at DESC);
